export const DISTRICTS = [
  { id: 'Ariyalur', en: 'Ariyalur', ta: 'அரியலூர்' },
  { id: 'Chengalpattu', en: 'Chengalpattu', ta: 'செங்கல்பட்டு' },
  { id: 'Chennai', en: 'Chennai', ta: 'சென்னை' },
  { id: 'Coimbatore', en: 'Coimbatore', ta: 'கோயம்புத்தூர்' },
  { id: 'Cuddalore', en: 'Cuddalore', ta: 'கடலூர்' },
  { id: 'Dharmapuri', en: 'Dharmapuri', ta: 'தருமபுரி' },
  { id: 'Dindigul', en: 'Dindigul', ta: 'திண்டுக்கல்' },
  { id: 'Erode', en: 'Erode', ta: 'ஈரோடு' },
  { id: 'Kallakurichi', en: 'Kallakurichi', ta: 'கள்ளக்குறிச்சி' },
  { id: 'Kanchipuram', en: 'Kanchipuram', ta: 'காஞ்சிபுரம்' },
  { id: 'Kanyakumari', en: 'Kanyakumari', ta: 'கன்னியாகுமரி' },
  { id: 'Karur', en: 'Karur', ta: 'கரூர்' },
  { id: 'Krishnagiri', en: 'Krishnagiri', ta: 'kவிருஷ்ணகிரி' },
  { id: 'Madurai', en: 'Madurai', ta: 'மதுரை' },
  { id: 'Mayiladuthurai', en: 'Mayiladuthurai', ta: 'மயிலாடுதுறை' },
  { id: 'Nagapattinam', en: 'Nagapattinam', ta: 'நாகப்பட்டினம்' },
  { id: 'Namakkal', en: 'Namakkal', ta: 'நாமக்கல்' },
  { id: 'Nilgiris', en: 'Nilgiris', ta: 'நீலகிரி' },
  { id: 'Perambalur', en: 'Perambalur', ta: 'பெரம்பலூர்' },
  { id: 'Pudukkottai', en: 'Pudukkottai', ta: 'புதுக்கோட்டை' },
  { id: 'Ramanathapuram', en: 'Ramanathapuram', ta: 'இராமநாதபுரம்' },
  { id: 'Ranipet', en: 'Ranipet', ta: 'இராணிப்பேட்டை' },
  { id: 'Salem', en: 'Salem', ta: 'சேலம்' },
  { id: 'Sivaganga', en: 'Sivaganga', ta: 'சிவகங்கை' },
  { id: 'Tenkasi', en: 'Tenkasi', ta: 'தென்காசி' },
  { id: 'Thanjavur', en: 'Thanjavur', ta: 'தஞ்சாவூர்' },
  { id: 'Theni', en: 'Theni', ta: 'தேனி' },
  { id: 'Thoothukudi', en: 'Thoothukudi', ta: 'தூத்துக்குடி' },
  { id: 'Tiruchirappalli', en: 'Tiruchirappalli', ta: 'திருச்சிராப்பள்ளி' },
  { id: 'Tirunelveli', en: 'Tirunelveli', ta: 'திருநெல்வேலி' },
  { id: 'Tirupathur', en: 'Tirupathur', ta: 'திருப்பத்தூர்' },
  { id: 'Tiruppur', en: 'Tiruppur', ta: 'திருப்பூர்' },
  { id: 'Tiruvallur', en: 'Tiruvallur', ta: 'திருவள்ளூர்' },
  { id: 'Tiruvannamalai', en: 'Tiruvannamalai', ta: 'திருவண்ணாமலை' },
  { id: 'Tiruvarur', en: 'Tiruvarur', ta: 'திருவாரூர்' },
  { id: 'Vellore', en: 'Vellore', ta: 'வேலூர்' },
  { id: 'Viluppuram', en: 'Viluppuram', ta: 'விழுப்புரம்' },
  { id: 'Virudhunagar', en: 'Virudhunagar', ta: 'விருதுநகர்' }
];

export const CONSTITUENCIES = [
  { id: 'Gummidipoondi', en: 'Gummidipoondi', ta: 'கும்மிடிப் பூண்டி' },
  { id: 'Ponneri', en: 'Ponneri', ta: 'பொன்னேரி' },
  { id: 'Tiruttani', en: 'Tiruttani', ta: 'திருத்தணி' },
  { id: 'Tiruvallur', en: 'Tiruvallur', ta: 'திருவள்ளூர்' },
  { id: 'Poonamallee', en: 'Poonamallee', ta: 'பூந்தமல்லி' },
  { id: 'Avadi', en: 'Avadi', ta: 'ஆவடி' },
  { id: 'Maduravoyal', en: 'Maduravoyal', ta: 'மதுரவாயல்' },
  { id: 'Ambattur', en: 'Ambattur', ta: 'அம்பத்தூர்' },
  { id: 'Madhavaram', en: 'Madhavaram', ta: 'மாதவரம்' },
  { id: 'Tiruvottiyur', en: 'Tiruvottiyur', ta: 'திருவொற்றியூர்' },
  { id: 'Dr. Radhakrishnan Nagar', en: 'Dr. Radhakrishnan Nagar', ta: 'டாக்டர் ராதாகிருஷ்ணன் நகர்' },
  { id: 'Perambur', en: 'Perambur', ta: 'பெரம்பூர்' },
  { id: 'Kolathur', en: 'Kolathur', ta: 'கொளத்தூர்' },
  { id: 'Villivakkam', en: 'Villivakkam', ta: 'வில்லிவாக்கம்' },
  { id: 'Thiru. Vi. Ka. Nagar', en: 'Thiru. Vi. Ka. Nagar', ta: 'திரு. வி. க. நகர்' },
  { id: 'Egmore', en: 'Egmore', ta: 'எழும்பூர்' },
  { id: 'Royapuram', en: 'Royapuram', ta: 'ராயபுரம்' },
  { id: 'Harbour', en: 'Harbour', ta: 'துறைமுகம்' },
  { id: 'Chepauk-Triplicane', en: 'Chepauk-Triplicane', ta: 'சேப்பாக்கம்-திருவல்லிக்கேணி' },
  { id: 'Thousand Lights', en: 'Thousand Lights', ta: 'ஆயிரம் விளக்கு' },
  { id: 'Anna Nagar', en: 'Anna Nagar', ta: 'அண்ணா நகர்' },
  { id: 'Virugambakkam', en: 'Virugambakkam', ta: 'விருகம்பாக்கம்' },
  { id: 'Saidapet', en: 'Saidapet', ta: 'சைதாப்பேட்டை' },
  { id: 'T. Nagar', en: 'T. Nagar', ta: 'தியாகராய நகர்' },
  { id: 'Mylapore', en: 'Mylapore', ta: 'மயிலாப்பூர்' },
  { id: 'Velachery', en: 'Velachery', ta: 'வேளச்சேரி' },
  { id: 'Sholinganallur', en: 'Sholinganallur', ta: 'சோழிங்கநல்லூர்' },
  { id: 'Alandur', en: 'Alandur', ta: 'ஆலந்தூர்' },
  { id: 'Sriperumbudur', en: 'Sriperumbudur', ta: 'ஸ்ரீபெரும்புதூர்' },
  { id: 'Pallavaram', en: 'Pallavaram', ta: 'பல்லாவரம்' },
  { id: 'Tambaram', en: 'Tambaram', ta: 'தாம்பரம்' },
  { id: 'Chengalpattu', en: 'Chengalpattu', ta: 'செங்கல்பட்டு' },
  { id: 'Thiruporur', en: 'Thiruporur', ta: 'திருப்போரூர்' },
  { id: 'Cheyyur', en: 'Cheyyur', ta: 'செய்யூர்' },
  { id: 'Maduranthakam', en: 'Maduranthakam', ta: 'மதுராந்தகம்' },
  { id: 'Utiramerur', en: 'Utiramerur', ta: 'உத்திரமேரூர்' },
  { id: 'Kancheepuram', en: 'Kancheepuram', ta: 'காஞ்சிபுரம்' },
  { id: 'Arakkonam', en: 'Arakkonam', ta: 'அரக்கோணம்' },
  { id: 'Sholingur', en: 'Sholingur', ta: 'சோளிங்கர்' },
  { id: 'Katpadi', en: 'Katpadi', ta: 'காட்பாடி' },
  { id: 'Ranipet', en: 'Ranipet', ta: 'ராணிப்பேட்டை' },
  { id: 'Arcot', en: 'Arcot', ta: 'ஆற்காடு' },
  { id: 'Vellore', en: 'Vellore', ta: 'வேலூர்' },
  { id: 'Anaikattu', en: 'Anaikattu', ta: 'அணைக்கட்டு' },
  { id: 'Kilvaithinankuppam', en: 'Kilvaithinankuppam', ta: 'கீழ்வைத்தியனான்குப்பம்' },
  { id: 'Gudiyattam', en: 'Gudiyattam', ta: 'குடியாத்தம்' },
  { id: 'Vaniyambadi', en: 'Vaniyambadi', ta: 'வாணியம்பாடி' },
  { id: 'Ambur', en: 'Ambur', ta: 'ஆம்பூர்' },
  { id: 'Jolarpet', en: 'Jolarpet', ta: 'ஜோலார்பேட்டை' },
  { id: 'Tirupattur', en: 'Tirupattur', ta: 'திருப்பத்தூர்' },
  { id: 'Uthangarai', en: 'Uthangarai', ta: 'உத்தங்கரை' },
  { id: 'Bargur', en: 'Bargur', ta: 'பர்கூர்' },
  { id: 'Krishnagiri', en: 'Krishnagiri', ta: 'கிருஷ்ணகிரி' },
  { id: 'Veppanahalli', en: 'Veppanahalli', ta: 'வேப்பனஹள்ளி' },
  { id: 'Hosur', en: 'Hosur', ta: 'ஓசூர்' },
  { id: 'Thalli', en: 'Thalli', ta: 'தளி' },
  { id: 'Shoolagiri', en: 'Shoolagiri', ta: 'சூளகிரி' },
  { id: 'Palacode', en: 'Palacode', ta: 'பாலக்கோடு' },
  { id: 'Pennagaram', en: 'Pennagaram', ta: 'பெண்ணாகரம்' },
  { id: 'Dharmapuri', en: 'Dharmapuri', ta: 'தருமபுரி' },
  { id: 'Pappireddipatti', en: 'Pappireddipatti', ta: 'பாப்பிரெட்டிப்பட்டி' },
  { id: 'Harur', en: 'Harur', ta: 'அரூர்' },
  { id: 'Chengam', en: 'Chengam', ta: 'செங்கம்' },
  { id: 'Tiruvannamalai', en: 'Tiruvannamalai', ta: 'திருவண்ணாமலை' },
  { id: 'Kilpennathur', en: 'Kilpennathur', ta: 'கீழ்பென்னாத்தூர்' },
  { id: 'Kalasapakkam', en: 'Kalasapakkam', ta: 'கலசப்பாக்கம்' },
  { id: 'Polur', en: 'Polur', ta: 'போளூர்' },
  { id: 'Arani', en: 'Arani', ta: 'ஆரணி' },
  { id: 'Cheyyar', en: 'Cheyyar', ta: 'செய்யாறு' },
  { id: 'Vandavasi', en: 'Vandavasi', ta: 'வந்தவாசி' },
  { id: 'Gingee', en: 'Gingee', ta: 'செஞ்சி' },
  { id: 'Mailam', en: 'Mailam', ta: 'மயிலம்' },
  { id: 'Tindivanam', en: 'Tindivanam', ta: 'திண்டிவனம்' },
  { id: 'Vanur', en: 'Vanur', ta: 'வானூர்' },
  { id: 'Villupuram', en: 'Villupuram', ta: 'விழுப்புரம்' },
  { id: 'Vikravandi', en: 'Vikravandi', ta: 'விக்ரவாண்டி' },
  { id: 'Tirukkoyilur', en: 'Tirukkoyilur', ta: 'திருக்கோவிலூர்' },
  { id: 'Ulundurpet', en: 'Ulundurpet', ta: 'உளுந்தூர்ப்பேட்டை' },
  { id: 'Rishivandiyam', en: 'Rishivandiyam', ta: 'ரிஷிவந்தியம்' },
  { id: 'Sankarapuram', en: 'Sankarapuram', ta: 'சங்கராபுரம்' },
  { id: 'Kallakurichi', en: 'Kallakurichi', ta: 'கள்ளக்குறிச்சி' },
  { id: 'Gangavalli', en: 'Gangavalli', ta: 'கெங்கவல்லி' },
  { id: 'Attur', en: 'Attur', ta: 'ஆத்தூர்' },
  { id: 'Yercaud', en: 'Yercaud', ta: 'ஏற்காடு' },
  { id: 'Omalur', en: 'Omalur', ta: 'ஓமலூர்' },
  { id: 'Mettur', en: 'Mettur', ta: 'மேட்டூர்' },
  { id: 'Edappadi', en: 'Edappadi', ta: 'இடப்பாடி' },
  { id: 'Sankari', en: 'Sankari', ta: 'சங்ககிரி' },
  { id: 'Salem West', en: 'Salem West', ta: 'சேலம் மேற்கு' },
  { id: 'Salem North', en: 'Salem North', ta: 'சேலம் வடக்கு' },
  { id: 'Salem South', en: 'Salem South', ta: 'சேலம் தெற்கு' },
  { id: 'Veerapandi', en: 'Veerapandi', ta: 'வீரபாண்டி' },
  { id: 'Rasipuram', en: 'Rasipuram', ta: 'ராசிபுரம்' },
  { id: 'Senthamangalam', en: 'Senthamangalam', ta: 'சேந்தமங்கலம்' },
  { id: 'Namakkal', en: 'Namakkal', ta: 'நாமக்கல்' },
  { id: 'Paramathi Velur', en: 'Paramathi Velur', ta: 'பரமத்தி வேலூர்' },
  { id: 'Tiruchengodu', en: 'Tiruchengodu', ta: 'திருச்செங்கோடு' },
  { id: 'Kumarapalayam', en: 'Kumarapalayam', ta: 'குமாரபாளையம்' },
  { id: 'Erode East', en: 'Erode East', ta: 'ஈரோடு கிழக்கு' },
  { id: 'Erode West', en: 'Erode West', ta: 'ஈரோடு மேற்கு' },
  { id: 'Modakkurichi', en: 'Modakkurichi', ta: 'மொடக்குறிச்சி' },
  { id: 'Dharapuram', en: 'Dharapuram', ta: 'தாராபுரம்' },
  { id: 'Kangayam', en: 'Kangayam', ta: 'காங்கேயம்' },
  { id: 'Perundurai', en: 'Perundurai', ta: 'பெருந்துறை' },
  { id: 'Bhavani', en: 'Bhavani', ta: 'பவானி' },
  { id: 'Anthiyur', en: 'Anthiyur', ta: 'அந்தியூர்' },
  { id: 'Gobichettipalayam', en: 'Gobichettipalayam', ta: 'கோபிசெட்டிபாளையம்' },
  { id: 'Bhavanisagar', en: 'Bhavanisagar', ta: 'பவானிசாகர்' },
  { id: 'Udhagamandalam', en: 'Udhagamandalam', ta: 'உதகமண்டலம்' },
  { id: 'Gudalur', en: 'Gudalur', ta: 'கூடலூர்' },
  { id: 'Coonoor', en: 'Coonoor', ta: 'குன்னூர்' },
  { id: 'Mettupalayam', en: 'Mettupalayam', ta: 'மேட்டுப்பாளையம்' },
  { id: 'Sulur', en: 'Sulur', ta: 'சூலூர்' },
  { id: 'Kavundampalayam', en: 'Kavundampalayam', ta: 'கவுண்டம்பாளையம்' },
  { id: 'Coimbatore North', en: 'Coimbatore North', ta: 'கோயம்புத்தூர் வடக்கு' },
  { id: 'Coimbatore South', en: 'Coimbatore South', ta: 'கோயம்புத்தூர் தெற்கு' },
  { id: 'Singanallur', en: 'Singanallur', ta: 'சிங்காநல்லூர்' },
  { id: 'Kinathukadavu', en: 'Kinathukadavu', ta: 'கிணத்துக்கடவு' },
  { id: 'Pollachi', en: 'Pollachi', ta: 'பொள்ளாச்சி' },
  { id: 'Valparai', en: 'Valparai', ta: 'வால்பாறை' },
  { id: 'Tiruppur North', en: 'Tiruppur North', ta: 'திருப்பூர் வடக்கு' },
  { id: 'Tiruppur South', en: 'Tiruppur South', ta: 'திருப்பூர் தெற்கு' },
  { id: 'Palladam', en: 'Palladam', ta: 'பல்லடம்' },
  { id: 'Udumalaipettai', en: 'Udumalaipettai', ta: 'உடுமலைப்பேட்டை' },
  { id: 'Madathukulam', en: 'Madathukulam', ta: 'மடத்துக்குளம்' },
  { id: 'Palani', en: 'Palani', ta: 'பழனி' },
  { id: 'Oddanchatram', en: 'Oddanchatram', ta: 'ஒட்டன்சத்திரம்' },
  { id: 'Athoor', en: 'Athoor', ta: 'ஆத்தூர்' },
  { id: 'Dindigul', en: 'Dindigul', ta: 'திண்டுக்கல்' },
  { id: 'Vedasandur', en: 'Vedasandur', ta: 'வேடசந்தூர்' },
  { id: 'Natham', en: 'Natham', ta: 'நத்தம்' },
  { id: 'Nilakottai', en: 'Nilakottai', ta: 'நிலக்கோட்டை' },
  { id: 'Cumbum', en: 'Cumbum', ta: 'கம்பம்' },
  { id: 'Periyakulam', en: 'Periyakulam', ta: 'பெரியகுளம்' },
  { id: 'Bodinayakanur', en: 'Bodinayakanur', ta: 'போடிநாயக்கனூர்' },
  { id: 'Andipatti', en: 'Andipatti', ta: 'ஆண்டிபட்டி' },
  { id: 'Usilampatti', en: 'Usilampatti', ta: 'உசிலம்பட்டி' },
  { id: 'Sholavandan', en: 'Sholavandan', ta: 'சோழவந்தான்' },
  { id: 'Madurai East', en: 'Madurai East', ta: 'மதுரை கிழக்கு' },
  { id: 'Madurai West', en: 'Madurai West', ta: 'மதுரை மேற்கு' },
  { id: 'Madurai Central', en: 'Madurai Central', ta: 'மதுரை மத்தி' },
  { id: 'Madurai South', en: 'Madurai தெற்கு' },
  { id: 'Melur', en: 'Melur', ta: 'மேலூர்' },
  { id: 'Madurai North', en: 'Madurai வடக்கு' },
  { id: 'Thirumangalam', en: 'Thirumangalam', ta: 'திருமங்கலம்' },
  { id: 'Tirupparankundram', en: 'Tirupparankundram', ta: 'திருப்பரங்குன்றம்' },
  { id: 'Thiruvadanai', en: 'Thiruvadanai', ta: 'திருவாடானை' },
  { id: 'Paramakudi', en: 'Paramakudi', ta: 'பரமக்குடி' },
  { id: 'Ramanathapuram', en: 'Ramanathapuram', ta: 'இராமநாதபுரம்' },
  { id: 'Mudukulathur', en: 'Mudukulathur', ta: 'முதுகுளத்தூர்' },
  { id: 'Tiruchuli', en: 'Tiruchuli', ta: 'திருச்சுழி' },
  { id: 'Aruppukottai', en: 'Aruppukottai', ta: 'அருப்புக்கோட்டை' },
  { id: 'Virudhunagar', en: 'Virudhunagar', ta: 'விருதுநகர்' },
  { id: 'Sivakasi', en: 'Sivakasi', ta: 'சிவகாசி' },
  { id: 'Srivilliputhur', en: 'Srivilliputhur', ta: 'ஸ்ரீவில்லிபுத்தூர்' },
  { id: 'Rajapalayam', en: 'Rajapalayam', ta: 'ராஜபாளையம்' },
  { id: 'Sattur', en: 'Sattur', ta: 'சாத்தூர்' },
  { id: 'Vilathikulam', en: 'Vilathikulam', ta: 'விளாத்திகுளம்' },
  { id: 'Thoothukudi', en: 'Thoothukudi', ta: 'தூத்துக்குடி' },
  { id: 'Tiruchendur', en: 'Tiruchendur', ta: 'திருச்செந்தூர்' },
  { id: 'Srivaikuntam', en: 'Srivaikuntam', ta: 'ஸ்ரீவைகுண்டம்' },
  { id: 'Ottapidaram', en: 'Ottapidaram', ta: 'ஒட்டப்பிடாரம்' },
  { id: 'Kovilpatti', en: 'Kovilpatti', ta: 'கோவில்பட்டி' },
  { id: 'Sankarankovil', en: 'Sankarankovil', ta: 'சங்கரன்கோவில்' },
  { id: 'Vasudevanallur', en: 'Vasudevanallur', ta: 'வாசுதேவநல்லூர்' },
  { id: 'Kadayanallur', en: 'Kadayanallur', ta: 'கடையநல்லூர்' },
  { id: 'Tenkasi', en: 'Tenkasi', ta: 'தென்காசி' },
  { id: 'Alangulam', en: 'Alangulam', ta: 'ஆலங்குளம்' },
  { id: 'Tirunelveli', en: 'Tirunelveli', ta: 'திருநெல்வேலி' },
  { id: 'Ambasamudram', en: 'Ambasamudram', ta: 'அம்பாசமுத்திரம்' },
  { id: 'Nanguneri', en: 'Nanguneri', ta: 'நாங்குநேரி' },
  { id: 'Radhapuram', en: 'Radhapuram', ta: 'ராதாபுரம்' },
  { id: 'Palayamkottai', en: 'Palayamkottai', ta: 'பாளையங்கோட்டை' },
  { id: 'Kanyakumari', en: 'Kanyakumari', ta: 'கன்னியாகுமரி' },
  { id: 'Nagercoil', en: 'Nagercoil', ta: 'நாகர்கோவில்' },
  { id: 'Colachel', en: 'Colachel', ta: 'குளச்சல்' },
  { id: 'Padmanabhapuram', en: 'Padmanabhapuram', ta: 'பத்மநாபபுரம்' },
  { id: 'Vilavancode', en: 'Vilavancode', ta: 'விளவங்கோடு' },
  { id: 'Killiyoor', en: 'Killiyoor', ta: 'கிள்ளியூர்' }
];

export const TAMIL_COMMUNITIES = [
  { id: 'Kallar', en: 'Kallar', ta: 'கள்ளர்' },
  { id: 'Maravar', en: 'Maravar', ta: 'மறவர்' },
  { id: 'Agamudaiyar', en: 'Agamudaiyar', ta: 'அகமுடையார்' },
  { id: 'Konar', en: 'Konar', ta: 'கோனார்' },
  { id: 'Idaiyar', en: 'Idaiyar', ta: 'இடையர்' },
  { id: 'Ayar', en: 'Ayar', ta: 'ஆயர்' },
  { id: 'Vellalar', en: 'Vellalar', ta: 'வேளாளர்' },
  { id: 'Karkathar', en: 'Karkathar', ta: 'கார்காத்தர்' },
  { id: 'Sengunthar (Kaikolar)', en: 'Sengunthar (Kaikolar)', ta: 'செங்குந்தர் (கைகோளர்)' },
  { id: 'Nadar', en: 'Nadar', ta: 'நாடார்' },
  { id: 'Vanniyar', en: 'Vanniyar', ta: 'வன்னியர்' },
  { id: 'Muthuraja', en: 'Muthuraja', ta: 'முத்துராஜா' },
  { id: 'Devanga', en: 'Devanga', ta: 'தேவாங்கர்' },
  { id: 'Kammalar', en: 'Kammalar', ta: 'கம்மாளர்' },
  { id: 'Kuyavar', en: 'Kuyavar', ta: 'குயவர்' },
  { id: 'Vannar', en: 'Vannar', ta: 'வண்ணார்' },
  { id: 'Navithar', en: 'Navithar', ta: 'நாவிதர்' },
  { id: 'Paravar', en: 'Paravar', ta: 'பரவர்' },
  { id: 'Pattinavar', en: 'Pattinavar', ta: 'பட்டினவர்' },
  { id: 'Mukkuvar', en: 'Mukkuvar', ta: 'முக்குவர்' },
  { id: 'Karaiyar', en: 'Karaiyar', ta: 'கரையார்' },
  { id: 'Kuravar', en: 'Kuravar', ta: 'குறவர்' },
  { id: 'Vallambar', en: 'Vallambar', ta: 'வள்ளம்பர்' },
  { id: 'Nattaman', en: 'Nattaman', ta: 'நத்தமான்' },
  { id: 'Ambalakarar', en: 'Ambalakarar', ta: 'அம்பலகாரர்' },
  { id: 'Odar', en: 'Odar', ta: 'ஓடார்' },
  { id: 'Saurashtrian', en: 'Saurashtrian', ta: 'சௌராஷ்டிரியர்' },
  { id: 'Brahmin', en: 'Brahmin', ta: 'பிராமணர்' },
  { id: 'Paraiyar', en: 'Paraiyar', ta: 'பறையர்' },
  { id: 'Pallar', en: 'Pallar', ta: 'பள்ளர்' },
  { id: 'Arunthathiyar', en: 'Arunthathiyar', ta: 'அருந்ததியர்' },
  { id: 'Chakkiliyar', en: 'Chakkiliyar', ta: 'சக்கிலியர்' },
  { id: 'Other', en: 'Other', ta: 'மற்றவை' }
];
